services:
  java-app:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - java-db

  java-db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - java-db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  java-nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - java-app

volumes:
  java-db-data:
